# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.pcm.v1 import pcm_pb2 as pcm_dot_v1_dot_pcm__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pcm/v1/pcm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PcmProcessorStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessStream = channel.unary_stream(
                '/pcm.v1.PcmProcessor/ProcessStream',
                request_serializer=pcm_dot_v1_dot_pcm__pb2.ProcessRequest.SerializeToString,
                response_deserializer=pcm_dot_v1_dot_pcm__pb2.ProcessSegment.FromString,
                _registered_method=True)
        self.Check = channel.unary_unary(
                '/pcm.v1.PcmProcessor/Check',
                request_serializer=pcm_dot_v1_dot_pcm__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=pcm_dot_v1_dot_pcm__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class PcmProcessorServicer:
    """Missing associated documentation comment in .proto file."""

    def ProcessStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PcmProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ProcessStream,
                    request_deserializer=pcm_dot_v1_dot_pcm__pb2.ProcessRequest.FromString,
                    response_serializer=pcm_dot_v1_dot_pcm__pb2.ProcessSegment.SerializeToString,
            ),
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=pcm_dot_v1_dot_pcm__pb2.HealthCheckRequest.FromString,
                    response_serializer=pcm_dot_v1_dot_pcm__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pcm.v1.PcmProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pcm.v1.PcmProcessor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PcmProcessor:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pcm.v1.PcmProcessor/ProcessStream',
            pcm_dot_v1_dot_pcm__pb2.ProcessRequest.SerializeToString,
            pcm_dot_v1_dot_pcm__pb2.ProcessSegment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pcm.v1.PcmProcessor/Check',
            pcm_dot_v1_dot_pcm__pb2.HealthCheckRequest.SerializeToString,
            pcm_dot_v1_dot_pcm__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
