# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pcm/v1/pcm.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'pcm/v1/pcm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10pcm/v1/pcm.proto\x12\x06pcm.v1\"\x81\x01\n\x0eProcessRequest\x12\x11\n\tpcm_s16le\x18\x01 \x01(\x0c\x12\x0f\n\x07gain_db\x18\x02 \x01(\x01\x12\x14\n\x0c\x64uration_sec\x18\x03 \x01(\x01\x12\x19\n\x11input_sample_rate\x18\x04 \x01(\x05\x12\x1a\n\x12output_sample_rate\x18\x05 \x01(\x05\"i\n\x0eProcessSegment\x12\x11\n\tpcm_s16le\x18\x01 \x01(\x0c\x12\x15\n\rsegment_index\x18\x02 \x01(\x05\x12\x1c\n\x14segment_duration_sec\x18\x03 \x01(\x01\x12\x0f\n\x07is_last\x18\x04 \x01(\x08\"\x14\n\x12HealthCheckRequest\"%\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x93\x01\n\x0cPcmProcessor\x12\x41\n\rProcessStream\x12\x16.pcm.v1.ProcessRequest\x1a\x16.pcm.v1.ProcessSegment0\x01\x12@\n\x05\x43heck\x12\x1a.pcm.v1.HealthCheckRequest\x1a\x1b.pcm.v1.HealthCheckResponseB\x13\n\x0f\x63om.demo.pcm.v1P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pcm.v1.pcm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017com.demo.pcm.v1P\001'
  _globals['_PROCESSREQUEST']._serialized_start=29
  _globals['_PROCESSREQUEST']._serialized_end=158
  _globals['_PROCESSSEGMENT']._serialized_start=160
  _globals['_PROCESSSEGMENT']._serialized_end=265
  _globals['_HEALTHCHECKREQUEST']._serialized_start=267
  _globals['_HEALTHCHECKREQUEST']._serialized_end=287
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=289
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=326
  _globals['_PCMPROCESSOR']._serialized_start=329
  _globals['_PCMPROCESSOR']._serialized_end=476
# @@protoc_insertion_point(module_scope)
